name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t product-service:latest .

      - name: Run Go Tests with Coverage
        run: |
          docker run product-service:latest sh -c "
            cd /app/pkg/services && 
            ls && 
            go test -cover ./...
          " 

      - name: Push to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag product-service:latest ericamaya29/product-service:latest
      - run: docker push ericamaya29/product-service:latest